# Generated by Django 4.2 on 2024-02-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='50612', max_length=5, verbose_name='Код верификации'),
        ),
    ]
