# Generated by Django 4.2 on 2024-02-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='45763', max_length=5, verbose_name='Код верификации'),
        ),
    ]
